# version: '3'

services:
  node-app:
    build:
      context: .
    container_name: api
    depends_on:
      - postgres
    ports:
      - 5002:3000
    env_file:
      - .env
    networks:
      - alt-sch-network
    volumes:
      - .:/var/www/

  postgres:
    restart: always
    image: postgres
    container_name: api-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stoic_elgamal
    ports:
      - 5030:5432
    volumes:
      - ./docker-db/scripts/db:/scripts
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - alt-sch-network
  
networks:
 alt-sch-network:
