# version: '3'

services:
  api:
    build:
      context: .
    container_name: api
    depends_on:
      - postgres
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DB_USER=
      - DB_PORT=
      - DB_PASS=
      - DB_HOST=
      - JWT_SECRET=
      - JWT_ISSUER=
      - JWT_AUDIENCE=
      - JWT_EXPIRES_IN=1h
      - JWT_ALGORITHM=HS256
      - JWT_REFRESH_EXPIRES_IN=7d
    volumes:
      - .:/var/www/

  postgres:
    restart: always
    image: postgres:12-alpine
    container_name: api-db
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - 5432:5432
    volumes:
      - ./docker-db/scripts/db:/scripts
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
